'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Loginpage.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property books_wooden_background_open_book_149422910() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("books-wooden-background-open-book-149422910", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property books_wooden_background_open_book_1494229101() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("books-wooden-background-open-book-1494229101", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property leather_book_over_wooden_table_books_background_pictures_wall_195791629() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leather-book-over-wooden-table-books-background-pictures-wall-195791629", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property leather_book_over_wooden_table_books_background_pictures_wall_1957916291() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("leather-book-over-wooden-table-books-background-pictures-wall-1957916291", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property library_background_wall_books_street_textured_pesaro_marche_italy_129421859() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("library-background-wall-books-street-textured-pesaro-marche-italy-129421859", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property library_background_wall_books_street_textured_pesaro_marche_italy_1294218591() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("library-background-wall-books-street-textured-pesaro-marche-italy-1294218591", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OIP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OIP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property old_books_white_wall_background_education_concept_vintage_tone_old_books_white_wall_background_education_concept_vintage_117417707() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("old-books-white-wall-background-education-concept-vintage-tone-old-books-white-wa"& _ 
                        "ll-background-education-concept-vintage-117417707", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property old_books_white_wall_background_education_concept_vintage_tone_old_books_white_wall_background_education_concept_vintage_1174177071() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("old-books-white-wall-background-education-concept-vintage-tone-old-books-white-wa"& _ 
                        "ll-background-education-concept-vintage-1174177071", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property open_book_light_bulb_hardback_books_wood_wall_background_free_space_text_selective_focus_open_book_light_bulb_111700990() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open-book-light-bulb-hardback-books-wood-wall-background-free-space-text-selectiv"& _ 
                        "e-focus-open-book-light-bulb-111700990", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property open_book_light_bulb_hardback_books_wood_wall_background_free_space_text_selective_focus_open_book_light_bulb_1117009901() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open-book-light-bulb-hardback-books-wood-wall-background-free-space-text-selectiv"& _ 
                        "e-focus-open-book-light-bulb-1117009901", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property thoughtful_young_man_book_his_hand_standing_library_loft_stone_wall_background_thoughtful_173214787() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thoughtful-young-man-book-his-hand-standing-library-loft-stone-wall-background-th"& _ 
                        "oughtful-173214787", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
